-- vim.o.errorbells      = false                       --- Disables sound effect for errors
-- vim.o.splitright      = true                        --- Vertical splits will automatically be to the right
-- vim.o.splitbelow      = true                        --- Horizontal splits will automatically be to the bottom
-- vim.o.updatetime      = 100                         --- Faster completion
-- vim.o.timeoutlen      = 300                         --- Faster completion
-- vim.o.redrawtime      = 10000
-- vim.o.ignorecase      = true                        --- Search case insensitive
-- vim.o.smartcase       = true                        --- Uses case in search
-- vim.bo.smartindent    = true                        --- Makes indenting smart
-- vim.bo.shiftwidth     = 4                           --- Change a number of space characeters inseted for indentation
-- vim.o.shiftwidth      = 4                           --- Change a number of space characeters inseted for indentation
-- vim.o.showtabline     = 2                           --- Always show tabs
-- vim.o.tabstop         = 4                           --- Insert 4 spaces for a tab
-- vim.bo.tabstop        = 4                           --- Insert 4 spaces for a tab
-- vim.o.softtabstop     = 4                           --- Insert 4 spaces for a tab
-- vim.bo.softtabstop    = 4                           --- Insert 4 spaces for a tab
-- vim.o.autoindent      = true                        --- Good auto indent
-- vim.wo.number         = true                        --- Shows current line number
-- vim.wo.relativenumber = true                        --- Enables relative number
-- vim.wo.cursorline     = true                        --- Highlight of current line
-- vim.wo.wrap           = false                       --- Display long lines as just one line
-- vim.o.undofile        = true                        --- Sets undo to file
-- vim.o.incsearch       = true                        --- Start searching before pressing enter
-- vim.o.conceallevel    = 0                           --- Show `` in markdown files
-- vim.o.backspace       = "indent,eol,start"          --- Making sure backspace works
-- vim.o.lazyredraw      = true                        --- Makes macros faster & prevent errors in complicated mappings
-- vim.o.wildignore      = "*node_modules/**"          --- Don't search inside Node.js modules (works for gutentag)
-- vim.o.scrolloff       = 8                           --- Always keep space when scrolling to bottom/top edge
-- vim.o.viminfo         = "'1000"                     --- Increase the size of file history
-- vim.o.termguicolors   = true                        --- Correct terminal colors
-- vim.o.signcolumn      = "yes"
--
-- vim.cmd('filetype plugin indent on') --- " Enables plugin & indent
-- vim.cmd('set shortmess+=c')          --- " Don't pass messages to |ins-completion-menu|
-- vim.cmd('set formatoptions-=c')      --- " Stop newline continuation of comments
-- vim.cmd('set formatoptions-=r')
-- vim.cmd('set formatoptions-=o')
-- vim.cmd('set expandtab')             --- Converts tab to spaces
-- vim.cmd('set completeopt=menuone,noselect')
-- vim.cmd('set noswapfile')
-- vim.cmd('set nobackup')
-- vim.cmd('set t_Co=256')
-- -- vim.cmd('set hlsearch')               --- Highlight found searches - enable this or nohlsearch
-- vim.cmd('set nohlsearch')             --- Don't highlight found searches - enable this or hlsearch
